name: 'Setup Java & Maven'
description: 'Sets up Java and Maven with caching'
inputs:
  java-version:
    description: 'Java version to use'
    required: true
  maven-version:
    description: 'Maven version to use'
    required: false
    default: '3.8.8'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Set up Maven
      run: echo "Maven ${{ inputs.maven-version }} setup"
