name: 'Setup Java & Maven'
description: 'Sets up Java and Maven with caching. Supports Java 11-25 (all LTS versions)'
inputs:
  java-version:
    description: 'Java version to use'
    required: true
  maven-version:
    description: 'Maven version to use'
    required: false
    default: '3.8.8'
  maven-opts:
    description: 'Additional options exported to MAVEN_OPTS'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Set up Maven
      shell: bash
      run: |
        echo "Using Maven version option: ${{ inputs.maven-version }}"
        if [ -n "${{ inputs.maven-opts }}" ]; then
          echo "Exporting MAVEN_OPTS=${{ inputs.maven-opts }}"
          echo "MAVEN_OPTS=${{ inputs.maven-opts }}" >> "$GITHUB_ENV"
        fi
        echo "Maven toolchain ready"
