name: 'Docker Build & Push'
description: 'Builds and pushes Docker images with multi-platform support'
inputs:
  image-name:
    description: 'Name of the Docker image'
    required: true
  image-tag:
    description: 'Tag for the Docker image'
    required: true
  registry:
    description: 'Container registry URL'
    required: false
    default: 'ghcr.io'
  push:
    description: 'Whether to push the image'
    required: false
    default: 'false'
  platforms:
    description: 'Comma-separated list of platforms'
    required: false
    default: 'linux/amd64'
  build-args:
    description: 'Build arguments for Docker'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
        build-args: ${{ inputs.build-args }}
